DROP TABLE IF EXISTS TUSER;

CREATE TABLE TUSER (
  USER_ID       CHAR(36),
  EMAIL         VARCHAR(25)  NOT NULL,
  PASSWORD      VARCHAR(25),
  CONSTRAINT unique_user_id PRIMARY KEY (USER_ID)
);


DROP TABLE IF EXISTS TROLE;
CREATE TABLE TROLE (
  ROLE_ID       CHAR(36),
  CONSTRAINT unique_role_id PRIMARY KEY (ROLE_ID)
);

CREATE TABLE USER_ROLE (
  USER_ID       CHAR(36),
  ROLE_ID       CHAR(36),
  CONSTRAINT unique_user_id_role_id PRIMARY KEY (USER_ID, ROLE_ID),
  FOREIGN KEY (USER_ID)
  REFERENCES TUSER (USER_ID),
  FOREIGN KEY (ROLE_ID)
  REFERENCES TROLE (ROLE_ID)
);
